const express=require('express')
const { body } = require("express-validator");
const router=express.Router()
const Adminvalidation=require('../middlewares/AdminValidation')
const AllowedTo=require('../middlewares/AllowedTo')
const AdminController=require('../Controllers/Admin.Controller')
const verifyToken = require('../middlewares/VerifyToken')

router.route('/doctors')
            .get(verifyToken,AllowedTo('admin','Patient'),AdminController.getAllDoctors)
            .post(verifyToken,AllowedTo('admin'),Adminvalidation.addDoctor,AdminController.AddDoctor)
router.route('/patients')
            .get(verifyToken,AllowedTo('admin','doctor'),AdminController.getAllPatients)
router.route('/:patientId')
            .get(verifyToken,AllowedTo('admin','doctor'),AdminController.getPatientById)
router.route('/:doctorId')
            .get(verifyToken,AllowedTo('admin','Patient'),AdminController.getDoctorById)
            .patch(verifyToken,AllowedTo('admin'),AdminController.UpdateDoctor)
            .delete(verifyToken,AllowedTo('admin'),AdminController.DeleteDoctor)
module.exports=router